title: Kyle's Awesome Blog
author: Kyle Barker
email: kwb600@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"

  This website is the amazing awesome blog of Kyle Barker
  
# social links
twitter_username: your-twitter-handle
github_username:  kwbarker

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
